### ISSUE TITLE
[Bug]: 示例 stockprice中，断开的连接不会被清理

### ISSUE THREAD

**Issue by BeanWei** [hertz-contrib/sse#6]
这个逻辑不会被触发，导致断开的连接无法清理掉

https://github.com/hertz-contrib/sse/blob/5621bf4d5fb9745aa75a5f6bab8ceedd22883d21/examples/server/stockprice/main.go#L162

sse(hertz?) 貌似没有任何机制可以感知到连接已断开？

**Comment by li-jin-gou** [comment]
这个 example 写的有问题

**Comment by BeanWei** [comment]
> 这个 example 写的有问题

这里面的示例基本都存在一定的问题。但是对于 `清理断开的连接` 这个问题，这个有解决方法吗，我没找到能够检测到链接断开的入口在哪

**Comment by li-jin-gou** [comment]
链接断开的话，写数据或读数据会返回 err

**Comment by BeanWei** [comment]
> 链接断开的话，写数据或读数据会返回 err

实际上并不会，我的认知以为它会返回error。那可能是 sse 的实现有问题

**Comment by BeanWei** [comment]
这行代码在 client 那边关闭连接时，写入数据依然没有err https://github.com/hertz-contrib/sse/blob/5621bf4d5fb9745aa75a5f6bab8ceedd22883d21/sse.go#L99

**Comment by li-jin-gou** [comment]
![img_v3_0255_042dff50-4dcc-43e0-be08-25ed8302285g](https://github.com/hertz-contrib/sse/assets/97824201/2a600d12-d780-4cf4-96bd-03961647460d)
![img_v3_0255_f3e84322-549e-404a-bff0-0779f222d56g](https://github.com/hertz-contrib/sse/assets/97824201/c3b4f374-1f9b-4f5f-93e3-7bb6e9ff73f0)

本地测试，返回了 err

**Comment by BeanWei** [comment]
> 本地测试，返回了 err

咦，我用 postman 和 curl 测试，客户端关闭后，写消息并没有返回err，我再检查下我的代码

**Comment by li-jin-gou** [comment]
我们尽快修复一下 example 的问题，sse server 在内部和外部都有很多用户真实场景使用的。

**Comment by BeanWei** [comment]
请问下上面截图使用的 hertz 是最新的版本么?

**Comment by BeanWei** [comment]
确实是我这边的问题，我在测试时使用的地址是走的 vite 代理的，先关了。

**Comment by li-jin-gou** [comment]
我重新打开一下，跟进 example 的进展
